package com.ca.cacore.rsss.model.vo;

import java.math.BigDecimal;

import com.newtouch.core.model.IPageCount;

public interface IAentLifeInsModel extends IPageCount{
	
	public String getBranch_id();
	public void setBranch_id(String branch_id);
	public String getOrg_id();
	public void setOrg_id(String org_id);
	public String getRisk_id();
	public void setRisk_id(String risk_id);
	public String getRisk_name();
	public void setRisk_name(String risk_name);
	public BigDecimal getNewpolicyfee();
	public void setNewpolicyfee(BigDecimal newpolicyfee);
	public BigDecimal getRenewalfee();
	public void setRenewalfee(BigDecimal renewalfee);
	public BigDecimal getPremium();
	public void setPremium(BigDecimal premium);
	public BigDecimal getNewpolicy_agcommiss();
	public void setNewpolicy_agcommiss(BigDecimal newpolicy_agcommiss);
	public BigDecimal getRenewal_agcommiss();
	public void setRenewal_agcommiss(BigDecimal renewal_agcommiss);
	public BigDecimal getAutotro_newpolicyfee();
	public void setAutotro_newpolicyfee(BigDecimal autotro_newpolicyfee);
	public BigDecimal getAutotro_renewalfee();
	public void setAutotro_renewalfee(BigDecimal autotro_renewalfee);
	public BigDecimal getAutotro_newpolicy_agcommiss();
	public void setAutotro_newpolicy_agcommiss(BigDecimal autotro_newpolicy_agcommiss);
	public BigDecimal getAutotro_renewal_agcommiss();
	public void setAutotro_renewal_agcommiss(BigDecimal autotro_renewal_agcommiss);
	public BigDecimal getTdparty_newpolicyfee();
	public void setTdparty_newpolicyfee(BigDecimal tdparty_newpolicyfee);
	public BigDecimal getTdparty_renewalfee();
	public void setTdparty_renewalfee(BigDecimal tdparty_renewalfee);
	public BigDecimal getTdparty_newpolicy_agcommiss();
	public void setTdparty_newpolicy_agcommiss(BigDecimal tdparty_newpolicy_agcommiss);
	public BigDecimal getTdparty_renewal_agcommiss();
	public void setTdparty_renewal_agcommiss(BigDecimal tdparty_renewal_agcommiss);
	public String getTerm();
	public void setTerm(String term);
	public String getSign_path();
	public void setSign_path(String sign_path);
	public String getDept_list();
	public void setDept_list(String dept_list);
	public BigDecimal getTotal_newpolfee();
	public void setTotal_newpolfee(BigDecimal total_newpolfee);
	public BigDecimal getTotal_renewfee();
	public void setTotal_renewfee(BigDecimal total_renewfee);
	public BigDecimal getTotal_permium();
	public void setTotal_permium(BigDecimal total_permium);
	public BigDecimal getTotal_newagent();
	public void setTotal_newagent(BigDecimal total_newagent);
	public BigDecimal getTotal_renewagent();
	public void setTotal_renewagent(BigDecimal total_renewagent);
	public BigDecimal getTotal_autonewpolfee();
	public void setTotal_autonewpolfee(BigDecimal total_autonewpolfee);
	public BigDecimal getTotal_auto_renewfee();
	public void setTotal_auto_renewfee(BigDecimal total_auto_renewfee);
	public BigDecimal getTotal_newagcommiss();
	public void setTotal_newagcommiss(BigDecimal total_newagcommiss);
	public BigDecimal getTotal_renewplofee();
	public void setTotal_renewplofee(BigDecimal total_renewplofee);
	public BigDecimal getTotal_tdnewplofee();
	public void setTotal_tdnewplofee(BigDecimal total_tdnewplofee);
	public BigDecimal getTotal_tdrenewfee();
	public void setTotal_tdrenewfee(BigDecimal total_tdrenewfee);
	public BigDecimal getTotal_newploagcommiss();
	public void setTotal_newploagcommiss(BigDecimal total_newploagcommiss);
	public BigDecimal getTotal_renewagcomiss() ;
	public void setTotal_renewagcomiss(BigDecimal total_renewagcomiss);
	public BigDecimal getPolicy_count();
	public void setPolicy_count(BigDecimal policy_count);
	public BigDecimal getAmount();
	public void setAmount(BigDecimal amount);
	public BigDecimal getPolicy_count_sum();
	public void setPolicy_count_sum(BigDecimal policy_count_sum);
	public BigDecimal getAmount_sum();
	public void setAmount_sum(BigDecimal amount_sum);
	public BigDecimal getNewpolicyfee_sum();
	public void setNewpolicyfee_sum(BigDecimal newpolicyfee_sum);
	public BigDecimal getRenewalfee_sum();
	public void setRenewalfee_sum(BigDecimal renewalfee_sum);
	public BigDecimal getPremium_sum();
	public void setPremium_sum(BigDecimal premium_sum);
	public BigDecimal getNewpolicy_agcommiss_sum();
	public void setNewpolicy_agcommiss_sum(BigDecimal newpolicy_agcommiss_sum);
	public BigDecimal getRenewal_agcommiss_sum();
	public void setRenewal_agcommiss_sum(BigDecimal renewal_agcommiss_sum);
	public BigDecimal getAutotro_newpolicyfee_sum();
	public void setAutotro_newpolicyfee_sum(BigDecimal autotro_newpolicyfee_sum);
	public BigDecimal getAutotro_renewalfee_sum();
	public void setAutotro_renewalfee_sum(BigDecimal autotro_renewalfee_sum);
	public BigDecimal getAutotro_newpolicy_agcommiss_sum();
	public void setAutotro_newpolicy_agcommiss_sum(BigDecimal autotro_newpolicy_agcommiss_sum);
	public BigDecimal getAutotro_renewal_agcommiss_sum();
	public void setAutotro_renewal_agcommiss_sum(BigDecimal autotro_renewal_agcommiss_sum);
	public BigDecimal getTdparty_newpolicyfee_sum();
	public void setTdparty_newpolicyfee_sum(BigDecimal tdparty_newpolicyfee_sum);
	public BigDecimal getTdparty_renewalfee_sum();
	public void setTdparty_renewalfee_sum(BigDecimal tdparty_renewalfee_sum);
	public BigDecimal getTdparty_newpolicy_agcommiss_sum();
	public void setTdparty_newpolicy_agcommiss_sum(BigDecimal tdparty_newpolicy_agcommiss_sum);
	public BigDecimal getTdparty_renewal_agcommiss_sum();
	public void setTdparty_renewal_agcommiss_sum(BigDecimal tdparty_renewal_agcommiss_sum);
	public BigDecimal getTotal_policy_count();
	public void setTotal_policy_count(BigDecimal total_policy_count);
	public BigDecimal getTotal_amount();
	public void setTotal_amount(BigDecimal total_amount);
	public BigDecimal getTotal_policycount_sum();
	public void setTotal_policycount_sum(BigDecimal total_policycount_sum);
	public BigDecimal getTotal_amount_sum();
	public void setTotal_amount_sum(BigDecimal total_amount_sum);
	public BigDecimal getTotal_newpolicyfee_sum();
	public void setTotal_newpolicyfee_sum(BigDecimal total_newpolicyfee_sum);
	public BigDecimal getTotal_renewalfee_sum();
	public void setTotal_renewalfee_sum(BigDecimal total_renewalfee_sum);
	public BigDecimal getTotal_premium_sum();
	public void setTotal_premium_sum(BigDecimal total_premium_sum);
	public BigDecimal getTotal_new_agcommiss_sum();
	public void setTotal_new_agcommiss_sum(BigDecimal total_new_agcommiss_sum);
	public BigDecimal getTotal_renew_agcommiss_sum();
	public void setTotal_renew_agcommiss_sum(BigDecimal total_renew_agcommiss_sum);
	public BigDecimal getTotal_autonewfee_sum();
	public void setTotal_autonewfee_sum(BigDecimal total_autonewfee_sum);
	public BigDecimal getTotal_autorenewfee_sum();
	public void setTotal_autorenewfee_sum(BigDecimal total_autorenewfee_sum);
	public BigDecimal getTotal_autonew_agcommiss_sum();
	public void setTotal_autonew_agcommiss_sum(BigDecimal total_autonew_agcommiss_sum);
	public BigDecimal getTotal_autorenew_agcommiss_sum();
	public void setTotal_autorenew_agcommiss_sum(BigDecimal total_autorenew_agcommiss_sum);
	public BigDecimal getTotal_tdnewfee_sum();
	public void setTotal_tdnewfee_sum(BigDecimal total_tdnewfee_sum);
	public BigDecimal getTotal_tdrenew_sum();
	public void setTotal_tdrenew_sum(BigDecimal total_tdrenew_sum);
	public BigDecimal getTotal_tdnew_agcommiss_sum();
	public void setTotal_tdnew_agcommiss_sum(BigDecimal total_tdnew_agcommiss_sum);
	public BigDecimal getTotal_tdrenew_agcommiss_sum();
	public void setTotal_tdrenew_agcommiss_sum(BigDecimal total_tdrenew_agcommiss_sum);
	
}
