package com.ca.cacore.rsss.model.vo;

import java.math.BigDecimal;

import com.newtouch.core.model.IPageCount;

public interface IAgentPropertyModel extends IPageCount{
	
	public String getBranch_id();
	public void setBranch_id(String branch_id);
	public String getOrg_id();
	public void setOrg_id(String org_id);
	public String getRisk_id();
	public void setRisk_id(String risk_id);
	public String getRisk_name();
	public void setRisk_name(String risk_name);
	public BigDecimal getPremium();
	public void setPremium(BigDecimal premium);
	public BigDecimal getPremium_payable();
	public void setPremium_payable(BigDecimal premium_payable);
	public BigDecimal getAgentcommission();
	public void setAgentcommission(BigDecimal agentcommission);
	public BigDecimal getAutotrophy_premium();
	public void setAutotrophy_premium(BigDecimal autotrophy_premium);
	public BigDecimal getAutotrophy_agentcommission();
	public void setAutotrophy_agentcommission(BigDecimal autotrophy_agentcommission);
	public BigDecimal getThirdparty_premium();
	public void setThirdparty_premium(BigDecimal thirdparty_premium);
	public BigDecimal getThirdparty_agentcommission();
	public void setThirdparty_agentcommission(BigDecimal thirdparty_agentcommission);
	public String getTerm();
	public void setTerm(String term);
	public String getSign_path();
	public void setSign_path(String sign_path);
	public String getDept_list();
	public void setDept_list(String dept_list);
	public BigDecimal getTotal_permium();
	public void setTotal_permium(BigDecimal total_permium);
	public BigDecimal getTotal_ppayable();
	public void setTotal_ppayable(BigDecimal total_ppayable);
	public BigDecimal getTotal_agcommiss();
	public void setTotal_agcommiss(BigDecimal total_agcommiss);
	public BigDecimal getTotal_autoprem();
	public void setTotal_autoprem(BigDecimal total_autoprem);
	public BigDecimal getTotal_autoagcommiss();
	public void setTotal_autoagcommiss(BigDecimal total_autoagcommiss);
	public BigDecimal getTotal_trdprem();
	public void setTotal_trdprem(BigDecimal total_trdprem);
	public BigDecimal getTotal_trdagcommiss();
	public void setTotal_trdagcommiss(BigDecimal total_trdagcommiss);
	public BigDecimal getPolicy_count();
	public void setPolicy_count(BigDecimal policy_count);
	public BigDecimal getAmount();
	public void setAmount(BigDecimal amount);
	public BigDecimal getPolicy_count_sum();
	public void setPolicy_count_sum(BigDecimal policy_count_sum);
	public BigDecimal getAmount_sum();
	public void setAmount_sum(BigDecimal amount_sum);
	public BigDecimal getPremium_sum();
	public void setPremium_sum(BigDecimal premium_sum);
	public BigDecimal getPremium_payable_sum();
	public void setPremium_payable_sum(BigDecimal premium_payable_sum);
	public BigDecimal getAgentcommission_sum();
	public void setAgentcommission_sum(BigDecimal agentcommission_sum);
	public BigDecimal getAutotrophy_premium_sum();
	public void setAutotrophy_premium_sum(BigDecimal autotrophy_premium_sum);
	public BigDecimal getAutotrophy_agentcommission_sum();
	public void setAutotrophy_agentcommission_sum(BigDecimal autotrophy_agentcommission_sum);
	public BigDecimal getThirdparty_premium_sum();
	public void setThirdparty_premium_sum(BigDecimal thirdparty_premium_sum);
	public BigDecimal getThirdparty_agentcommission_sum();
	public void setThirdparty_agentcommission_sum(BigDecimal thirdparty_agentcommission_sum);
	public BigDecimal getTotal_policy_count();
	public void setTotal_policy_count(BigDecimal total_policy_count);
	public BigDecimal getTotal_amount();
	public void setTotal_amount(BigDecimal total_amount);
	public BigDecimal getTotal_policycount_sum();
	public void setTotal_policycount_sum(BigDecimal total_policycount_sum);
	public BigDecimal getTotal_amount_sum();
	public void setTotal_amount_sum(BigDecimal total_amount_sum);
	public BigDecimal getTotal_permium_sum();
	public void setTotal_permium_sum(BigDecimal total_permium_sum);
	public BigDecimal getTotal_ppayable_sum();
	public void setTotal_ppayable_sum(BigDecimal total_ppayable_sum);
	public BigDecimal getTotal_agcommiss_sum();
	public void setTotal_agcommiss_sum(BigDecimal total_agcommiss_sum);
	public BigDecimal getTotal_autoprem_sum();
	public void setTotal_autoprem_sum(BigDecimal total_autoprem_sum);
	public BigDecimal getTotal_autoagcommiss_sum();
	public void setTotal_autoagcommiss_sum(BigDecimal total_autoagcommiss_sum);
	public BigDecimal getTotal_trdprem_sum();
	public void setTotal_trdprem_sum(BigDecimal total_trdprem_sum);
	public BigDecimal getTotal_trdagcommiss_sum();
	public void setTotal_trdagcommiss_sum(BigDecimal total_trdagcommiss_sum);

}
